### PR TITLE
fix: make sure `userRequest` stays unique (`module.userRequest`)

### LINKED ISSUE #49: NamedModulesPlugin breaks expose-loader from exposing the variable globally
The desired setup would be to have jquery exposed globally for plugins that require it (using expose-loader). HMR and NamedModulesPlugin allows for seeing the name of the modules that have been required to be reloaded.

Instead when adding expose-loader and NamedModulesPlugin, the global variable is no longer being added correctly and crashes the application.

Here is a minimal reproduction using jquery and velocity animate:

: https://github.com/NervosaX/webpack-namedmodulesplugin-error

### LINKED ISSUE #55: Setup via `webpack.config.js` file not working with NamedModulesPlugin
Reproduction - https://github.com/WiseBird/expose_loader_named_modules_plugin

I use `expose-loader` to expose jquery:
```
            {
                test: require.resolve('jquery'),
                use: [{
                    loader: 'expose-loader',
                    options: 'jQuery'
                }]
},
```

It works without `NamedModulesPlugin` while producing next output:
```
/* 88 */
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["jQuery"] = __webpack_require__(89);
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(1)))

/***/ }),
/* 89 */
/***/ (function(module, exports, __webpack_require__) {

var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;/*!
 * jQuery JavaScript Library v3.2.1
...
```

when `NamedModulesPlugin` is included output is following:
```
/***/ "./node_modules/jquery/dist/jquery.js":
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["jQuery"] = __webpack_require__("./node_modules/jquery/dist/jquery.js");
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__("./node_modules/webpack/buildin/global.js")))

/***/ }),

/***/ "./node_modules/jquery/dist/jquery.js":
/***/ (function(module, exports, __webpack_require__) {

var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;/*!
 * jQuery JavaScript Library v3.2.1
```

So both modules: the one exposing jquery and the one containing jquery have the same name.

Moreover when exposing via `require('expose-loader?jQuery!jquery');` the module exposing jquery have different name:
```
/***/ "./node_modules/expose-loader/index.js?jQuery!./node_modules/jquery/dist/jquery.js":
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["jQuery"] = __webpack_require__("./node_modules/jquery/dist/jquery.js");
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__("./node_modules/webpack/buildin/global.js")))

/***/ }),
```

`NamedModulesPlugin` [uses](https://github.com/webpack/webpack/blob/6cad87f5fecc0db52a0a0211beb64c68eda2cadb/lib/NamedModulesPlugin.js#L17) [`libIdent`](https://github.com/webpack/webpack/blob/c8fd542579c554409eb1202866755fa7be0bad51/lib/NormalModule.js#L91) from `NormalModule` that in its order uses `userRequest` that differs when library exposed via config file or via require statement.

### PR DESCRIPTION
**Pull request by timse**
### `Notable Changes`

There is an issue using expose loader in combination with `webpack.NamedModulesPlugin` as the userRequest that is used by webpack to calculate the named modules id stays the same.

See images below for explanation and fix:

screen shot 2017-11-14 at 11 09 46 am
screen shot 2017-11-14 at 11 09 57 am

### `Issues`

- Fixes #55 
- Fixes #49

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -32,6 +32,7 @@ module.exports.pitch = function(remainingRequest) {
 	);
 	this.cacheable && this.cacheable();
 	if(!this.query) throw new Error("query parameter is missing");
+	this._module.userRequest = this._module.userRequest + ' - exposed';
```
Comment (michael-ciniawsky) [inline index.js]: Could you please add a comment marking this is as a workaround until `module.libIdent()` gets fixed ? :)

**Comment by michael-ciniawsky** [comment]
Please sign the CLA by closing and reopening the PR to trigger the CLA Bot again :)

File: index.js (hunk 1 above)
Comment (timse) [reply index.js]: sure

**Comment by timse** [comment]
i signed it, see  => https://cla.js.foundation/webpack-contrib/expose-loader?pullRequest=58
not sure what else i can do 😛

**Comment by michael-ciniawsky** [comment]
Is the email used  by `git` (`.gitconfig`) && github account the same address?

**Comment by timse** [comment]
that was it :P sorry

**Comment by michael-ciniawsky** [comment]
@timse Thx again 👍

**Comment by timse** [comment]
np :)

can we release that?

**Comment by michael-ciniawsky** [comment]
Sry I can't cc @d3viant0ne :)

**Comment by d3viant0ne** [comment]
@timse - Sorry, missed this one. I'll have it out in 20 minutes.

**Comment by timse** [comment]
no worries @d3viant0ne and thnks for the release! :)
